[package]
name = "sctk_gtk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
gtk = "0.18"
smithay-client-toolkit = { version = "0.18.0", default_features = false }
tiny-skia = "0.11"
tracing = "0.1"
